name: SonarQube analysis for Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json -> using npm ci"
            npm ci
          else
            echo "No package-lock.json -> using npm install"
            npm install
          fi

      - name: Run tests with coverage
        run: |
          cd frontend
          npm test -- --watch=false --code-coverage

      - name: Build application
        run: |
          cd frontend
          npm run build -- --configuration production

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=birijepallisiva_angular-spring-boot-application
            -Dsonar.sources=frontend/src
            -Dsonar.tests=frontend/src
            -Dsonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.exclusions=node_modules/**,dist/**,**/*.json,frontend/coverage/**
            -Dsonar.projectBaseDir=frontend
